src/Entity/Game.php
<?php

namespace App\Entity;

use App\Repository\GameRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=GameRepository::class)
 */
class Game
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $playerNumber;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $minimumAge;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $Category;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $poster;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPlayerNumber(): ?int
    {
        return $this->playerNumber;
    }

    public function setPlayerNumber(?int $playerNumber): self
    {
        $this->playerNumber = $playerNumber;

        return $this;
    }

    public function getMinimumAge(): ?int
    {
        return $this->minimumAge;
    }

    public function setMinimumAge(?int $minimumAge): self
    {
        $this->minimumAge = $minimumAge;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->Category;
    }

    public function setCategory(?Category $Category): self
    {
        $this->Category = $Category;

        return $this;
    }

    public function getPoster(): ?string
    {
        return $this->poster;
    }

    public function setPoster(?string $poster): self
    {
        $this->poster = $poster;

        return $this;
    }
}

src/Form/GameType.php
<?php

namespace App\Form;

use App\Entity\Game;
use App\Entity\Category;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class GameType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, [
                'label' => 'nom du jeu',
                'attr' => ['placeholder' => 'Nom du jeu'],
                ])
            ->add('playerNumber', IntegerType::class, [
                'label' => 'Nombre de joueurs',
            ])
            ->add('minimumAge', IntegerType::class, [
                'label' => 'Age minimum',
            ])
            ->add('description', TextareaType::class, [
                'label' => "Description du jeu",
                'attr' => ['placeholder' => 'Expliquer le jeu'],
            ])
            ->add('Category', EntityType::class, [
                'class' => Category::class,
                'multiple' => false,
                'expanded' => true,
                'label' => 'Catégorie'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Game::class,
        ]);
    }
}

src/Controller/GameController.php
<?php

namespace App\Controller;

use App\Entity\Game;
use App\Form\GameType;
use App\Repository\GameRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/game", name="game_")
 */
class GameController extends AbstractController
{
    /**
    * Show all rows from game’s entity
    * @Route("/", name="index")
    * @return Response A response instance
    */
    public function index(): Response
    {
    $games = $this->getDoctrine()
    ->getRepository(Game::class)
    ->findAll();

    return $this->render(
    'game/index.html.twig',
    ['games' => $games]
    );
    }

    /**
     * @Route("/new", name="new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $game = new Game();
        $form = $this->createForm(GameType::class, $game);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($game);
            $entityManager->flush();

            return $this->redirectToRoute('game_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('game/new.html.twig', [
            'game' => $game,
            'form' => $form,
        ]);
    }

    /**
    * Getting a game by id
    *
    * @Route("/show/{id<^[0-9]+$>}", name="show")
    * @return Response
    */
    public function show(int $id):Response
    {
    $game = $this->getDoctrine()
    ->getRepository(Game::class)
    ->findOneBy(['id' => $id]);

    if (!$game) {
    throw $this->createNotFoundException(
    'No game with id : '.$id.' found in game\'s table.'
    );
    }
    return $this->render('game/show.html.twig', [
    'game' => $game,
    ]);
    }

    /**
     * @Route("/{id}/edit", name="edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Game $game): Response
    {
        $form = $this->createForm(GameType::class, $game);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('game_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('game/edit.html.twig', [
            'game' => $game,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="delete", methods={"POST"})
     */
    public function delete(Request $request, Game $game): Response
    {
        if ($this->isCsrfTokenValid('delete'.$game->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($game);
            $entityManager->flush();
        }

        return $this->redirectToRoute('game_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/game/_delete_form.html.twig
<form method="post" action="{{ path('game_delete', {'id': game.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ game.id) }}">
    <button class="btn">Delete</button>
</form>

templates/game/_form.html.twig
{{ form_start(form) }}
<div class="form">
    {{ form_widget(form) }}   
    <button class="btn">{{ button_label|default('envoyer') }}</button>
</div>
{{ form_end(form) }}

templates/game/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mise a jour du jeu{% endblock %}

{% block body %}
    <h1>Mise à jour du jeu</h1>

    {{ include('game/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('game_index') }}">Retour à la liste</a>

    {{ include('game/_delete_form.html.twig') }}
{% endblock %}

templates/game/index.html.twig
{% extends 'base.html.twig' %}


{% block title %}All games{% endblock %}


{% block body %}

    <h1>Tous nos jeux: </h1>
    <div class="ajoutjeudansjeu">
        <a href="{{ path('game_new') }}">Ajouter un nouveau jeu de société  la liste</a>
    </div>

    {% for game in games %}

        <div class="jeutheme">

            <h2>{{ loop.index }} / {{ game.name }} - Catégorie : {{ game.category.name }}</h2>

            <p>{{ game.description }}</p>
            {# Lien vers la fiche de la série : #}
            <a href="{{ path("game_show", { id: game.id }) }}">Voir la fiche</a>

        </div>

    {% else %}

        Aucun jeu trouvé.

    {% endfor %}

            <div class="buttonaccdansjeu">
                <a href="{{ path('app_index') }}">
                    
                    Retour à l'accueil
                    
                </a>
            </div>

{% endblock %}

templates/game/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau Jeu{% endblock %}

{% block body %}
    <h1>Enregistrer un nouveau jeu</h1>

    {{ include('game/_form.html.twig') }}

    <a href="{{ path('game_index') }}">Retour à la liste</a>
{% endblock %}

templates/game/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Jeu #{{ game.id }}{% endblock %}

{% block body %}
    <div class="media">
        <img class="align-self-start mr-3" src="{{game.poster}}" alt="{{ game.name }} poster">
    </div>

    <div class="media-body">
        <h1 class="mt-0">{{ game.name }}</h1>
        <p>{{ game.description }}</p>
        <p>Catégorie : {{ game.category.name }}</p>
    </div>
    
    <div id="retourjeu">
        <a href="{{ path('game_index') }}">Retour à la liste des jeux</a>
    </div>
    <div id="miseajourjeu">
        <a href="{{ path('game_edit', {'id': game.id}) }}">Mise à jour</a>
    </div>
    <div id="supprimerjeu">
        {{ include('game/_delete_form.html.twig') }}
    </div>
{% endblock %}